### ISSUE TITLE
Collision problem

### ISSUE THREAD

**Issue by DaGuT** [CodingTrain/Flappy-Bird-Clone#44]
Hola! With https://github.com/CodingTrain/Flappy-Bird-Clone/pull/43 there is now collision problem. You might not be touching the edge, but you'll loose (currently, there is a rectangle checking, however the image is not rectangled)

Also, in my personal opinion, https://github.com/CodingTrain/Flappy-Bird-Clone/pull/40/ is better. Also, it's free and made by user and commited at https://github.com/CodingTrain/Flappy-Bird-Clone/commit/5c6c6f009ffba0a55a10fd0f457e37b1f203ae4c :(
If we'd want to have those normal peaks, then there is a need to change collision (also it should be changed now). Current model is really bad :(

**Comment by A-Edusei** [comment]
Hi apologies for the late response to this issue. I can see the point you have made and have tested it out and as you mentioned there is a collision problem. I believe the issue lies within the transparency field that isn't displaying. With my uploaded design there is a transparent space that hasn't been drawn in causing this issue (I purposely left this space empty mostly due to the aesthetics of the new design of the pipes). As you know all uploaded images by default are uploaded as a square or rectangle transparent background which will still register a "HIT" even without a graphic or drawing within that space. I have come up with a solution which keeps the previous design I uploaded by slightly altering it but get rids of the transparent collision problem

**Comment by shiffman** [comment]
Resolved!
